#!/bin/sh

deps=
for d in deps/* ; do
  deps="$deps -pa $d/ebin"
done
exec erl \
  -name egm -setcookie egm \
  $deps \
  -pa ebin \
  -config mondemand_server_dev.config \
  -s reloader \
  -s mondemand_server_app
