#!/bin/sh

config=$1

if test "x$config" = "x" ; then
  config="dev"
fi

deps=
for d in deps/* ; do
  deps="$deps -pa $d/ebin"
done

cwd=`pwd -P`
pidfile="tmp/var/run/mondemand/rrdcached.pid"

getPid() {
  pid=`cat $pidfile`
}

startRRDCached() {
  mkdir -p tmp/logs
  touch tmp/logs/rrdcached.log
  rrdcached -b $cwd -B -R -l 127.0.0.1:11211 -s apache -f 7200 -w 3600 -p tmp/var/run/mondemand/rrdcached.pid -l unix:tmp/var/run/mondemand/rrdcached.sock -g  2>&1 >> tmp/logs/rrdcached.log &
}

if test -f $pidfile ; then
  getPid
  kill -0 $pid > /dev/null 2>&1
  if test $? = 0 ; then
    echo "rrdcached already running at $pid"
  else
    startRRDCached
  fi
else
  startRRDCached
fi

sleep 2

CONFIG=conf/mondemand_server_$config.config

rebar3 shell \
  --config $CONFIG \
  --setcookie md_server \
  --name "md_server_$config" \
  --apps "mondemand_server,mondemand_backend_stats_rrd"

num_running=`ps auwwx | grep beam | grep md_server | grep -v grep | wc -l`
if test $num_running -eq 0 -a -f $pidfile ; then
  getPid
  kill $pid
  rm -f $pidfile
fi
